config/routes.rb
Rails.application.routes.draw do
  devise_for :owners, controllers: { registrations: 'registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :buffets, only: [:index, :show, :new, :create, :edit, :update]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/buffet.rb
class Buffet < ApplicationRecord
  belongs_to :owner
  has_many :payments
  has_many :payment_methods, through: :payments
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :buffet
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :buffet
  belongs_to :payment_method
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  has_many :payments
  has_many :buffets, through: :payments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :buffet_not_registered_yet

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def buffet_not_registered_yet
    exception_routes = [destroy_owner_session_path, new_buffet_path, buffets_path]
    if current_owner && current_owner.buffet.nil?
      unless exception_routes.any? {|route| route == url_for(only_path: true)}
        redirect_to new_buffet_path
      end
    end
  end
end

app/controllers/buffets_controller.rb
class BuffetsController < ApplicationController
  before_action :authenticate_owner!, only: [:new, :edit]
  
  def index
    @buffets = Buffet.all
    @is_owner_without_buffet = current_owner && !current_owner.buffet
  end

  def show
    @buffet = Buffet.find(params[:id])
    @is_owner_valid = current_owner && @buffet.owner_id == current_owner.id
  end

  def new
    @buffet = Buffet.new
    @payment_methods = PaymentMethod.all
  end

  def edit
    @buffet = Buffet.find(params[:id])
    @payment_methods = PaymentMethod.all
  end

  def update
  end

  def create
    buffet_params = params.require(:buffet).permit(
      :brand,
      :corporate_name,
      :registration_number,
      :phone_number,
      :email,
      :address,
      :district,
      :state,
      :city,
      :zip_code,
      :description,
      payment_method_ids: []
    )
    @buffet = Buffet.new(buffet_params)
    @buffet.owner_id = current_owner.id
    @buffet.save!
    @buffet.payment_methods.each do |payment|
      print payment
    end
    redirect_to root_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(owner)
    new_buffet_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/buffets/_form.html.erb
<%= form_with model: @buffet do |f| %>
  <div>
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>
  <div>
    <%= f.label :corporate_name %>
    <%= f.text_field :corporate_name %>
  </div>
  <div>
    <%= f.label :registration_number %>
    <%= f.text_field :registration_number %>
  </div>
  <div>
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div>
    <%= f.label :district %>
    <%= f.text_field :district %>
  </div>
  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div>
    <br>
    <%= f.label :payment_method %>
    <br>
    <% @payment_methods.each do |payment_method| %>
      <%= check_box_tag payment_method.id %>
      <%= label_tag payment_method.id, payment_method.name %><br>
    <% end %>
  </div>

  <div>
    <%= f.submit "Cadastrar Buffet" %>
  </div>

<% end %>

app/views/buffets/edit.html.erb
<h2>Editar Buffet</h2>

<%= render 'form' %>

app/views/buffets/index.html.erb
<h2>Buffets</h2>

<%= @buffets.each do | buffet | %>
  <div>
    <%= link_to buffet.brand , buffet_path(buffet.id) %>
  </div>
<% end %>

<% if @is_owner_without_buffet %>
  <%= link_to "Cadastrar um Buffet", new_buffet_path %>
<% end %>

app/views/buffets/new.html.erb
<h2>Cadastrar Buffet</h2>

<%= render 'form' %>

app/views/buffets/show.html.erb
<h2><%= @buffet.brand %></h2>

<div>
  <span>Nome do Buffet:</span>
  <span><%= @buffet.brand %></span>
</div>
<div>
  <span>Endereço do Buffet:</span>
  <span><%= @buffet.address %></span>
</div>
<div>
  <span>Métodos de Pagamento:</span>
  <% @buffet.payment_methods.each do |payment_method| %>
    <%= payment_method.name %>
    <% unless payment_method == @buffet.payment_methods.last %> , <% end %>
  <% end %>  
</div>
<%if @is_owner_valid %>
  <%= link_to "Editar Buffet", edit_buffet_path(@buffet.id) %>
<% end %>

app/views/home/index.html.erb
<h2>Homepage</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewBuffet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <h1>Cadê Buffet</h1>
    </header>
    <nav>
      <%= link_to 'Buffets', buffets_path%>
      <% if owner_signed_in?%>
        <%= current_owner.email %>
        <%= button_to 'Sair', destroy_owner_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Entrar', new_owner_session_path %>
      <% end %>
    </nav>
    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>